[package]
name = "questionsample"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
serde = {version = "1", features = ["derive"] }
flatgeobuf = "3.24"
regex="1.7"
geo = "0.23"
gdal = "0.14"
geozero = "0.9"
